### PR TITLE
Fixed issues with factions being reset

### PR DESCRIPTION
**Pull request by JGelfand**
When I tried playing through this at first, Lazarus' faction had its recall list reset at level 4. I added save ids to fix this. I also made the placeholder factions on most maps hidden. I didn't actually end up testing the rest of the campaign before making the save id switch, but I'm guessing it would have had a similar issue on levels 11 and 14. In any case, I did test the campaign after making my changes to make sure everything still worked. I also fixed the deprecated description formatting on the 'Maternal' and 'Hidden' abilities. I encountered some broken wml code while playing through the Fair level. I'm guessing that my changes didn't break that, but if they did it would probably be due to the way that gold storage was previously handled.

### CODE REVIEW

**Comment by Benjamin-Waters** [comment]
One thing I'm noticing is that in some of the scenarios we're changing:
`controller=null`
but in others we are leaving it as:
`controller=human`

Any reason why this isn't a consistent change?

**Comment by JGelfand** [comment]
Ah- it looks like I forgot to change that in all of them. I thought it might help differentiate active sides from placeholders to future people who look at the code, but since there's no noticeable difference from the user's standpoint I must have missed that during testing.

**Comment by Benjamin-Waters** [comment]
Merged in, I'll add you to the contributors.

**Comment by JGelfand** [comment]
Cool! Thanks.

**Pull request merged**
